version: '2'
services:
    khidma-app:
        image: khidma
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://khidma-mysql:3306/khidma?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    khidma-mysql:
        extends:
            file: mysql.yml
            service: khidma-mysql
